import { User, Project, StudioSquad } from "./types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Aiko Tanaka",
    handle: "aiko.ink",
    avatarUrl: "https://i.pravatar.cc/256?img=5",
    role: "LINE_ARTIST",
    secondaryRoles: ["COLORIST"],
    bio: "Ex-Shueisha assistant. Seinen line work with brutal inks. Looking for a writer who loves morally gray cultivation arcs. I ship weekly, no ghosting — 98% completion.",
    genres: ["SEINEN", "CULTIVATION", "FANTASY"],
    formats: ["PAGE_MANGA", "VERTICAL_WEBTOON"],
    dealTypes: ["SWEAT_EQUITY_50_50", "PAID_GIG"],
    completionRate: 98,
    isVerified: true,
    ratingScore: 4.9,
    reviewCount: 34,
    completedProjects: 27,
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    location: "Osaka • JST",
    portfolio: [
      { id: "p1", title: "Blade of the Hollow — Ch.1", url: "https://picsum.photos/seed/manga1/800/1200", thumbnail: "https://picsum.photos/seed/manga1/400/600", format: "PAGE_MANGA", type: "image", pages: ["https://picsum.photos/seed/manga1a/800/1200","https://picsum.photos/seed/manga1b/800/1200","https://picsum.photos/seed/manga1c/800/1200"] },
      { id: "p2", title: "Neon Shrine — Vertical Teaser", url: "https://picsum.photos/seed/webtoon1/800/1400", thumbnail: "https://picsum.photos/seed/webtoon1/400/800", format: "VERTICAL_WEBTOON", type: "image" },
      { id: "p3", title: "Speedpaint: Ink Wash Duel", url: "https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4", thumbnail: "https://picsum.photos/seed/speed1/400/300", format: "PAGE_MANGA", type: "video" },
    ],
    vault: [
      { id: "v1", title: "30s — Blade Duel Speedpaint", url: "https://picsum.photos/seed/vault1/600/400", thumbnail: "https://picsum.photos/seed/vault1/600/400", duration: "0:32", type: "speedpaint" },
      { id: "v2", title: "Workflow: From Name to Final Inks", url: "https://picsum.photos/seed/vault2/600/400", thumbnail: "https://picsum.photos/seed/vault2/600/400", duration: "0:48", type: "workflow" },
    ]
  },
  {
    id: "u2",
    name: "Marcus Chen",
    handle: "marcuswrites",
    avatarUrl: "https://i.pravatar.cc/256?img=12",
    role: "WRITER",
    secondaryRoles: ["STORYBOARDER"],
    bio: "LitRPG & Isekai writer — 2M reads on Royal Road. I write tight outlines + dialogue, you bring the visuals. Looking for 50/50 pacts only. Fast reviser, loves feedback.",
    genres: ["LITRPG", "ISEKAI", "FANTASY"],
    formats: ["VERTICAL_WEBTOON"],
    dealTypes: ["SWEAT_EQUITY_50_50", "SKILL_SWAP"],
    completionRate: 94,
    isVerified: true,
    ratingScore: 4.8,
    reviewCount: 41,
    completedProjects: 19,
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    location: "Toronto • EST",
    portfolio: [
      { id: "p4", title: "Reborn as a Dungeon — Script Deck", url: "https://picsum.photos/seed/script1/800/1000", thumbnail: "https://picsum.photos/seed/script1/500/600", format: "VERTICAL_WEBTOON", type: "image" },
      { id: "p5", title: "World Bible — Cultivation System", url: "https://picsum.photos/seed/script2/800/1000", thumbnail: "https://picsum.photos/seed/script2/500/600", format: "VERTICAL_WEBTOON", type: "image" },
    ],
    vault: [
      { id: "v3", title: "Script Breakdown: Cold Open (60s)", url: "https://picsum.photos/seed/vault3/600/400", thumbnail: "https://picsum.photos/seed/vault3/600/400", duration: "1:02", type: "script_breakdown" },
    ]
  },
  {
    id: "u3",
    name: "Sofia Reyes",
    handle: "sofia.colors",
    avatarUrl: "https://i.pravatar.cc/256?img=32",
    role: "COLORIST",
    secondaryRoles: ["LINE_ARTIST"],
    bio: "Manhwa colorist — soft otome palettes meets horror shadows. Webtoon Canvas Featured. Seeking shōjo/cultivation teams. Vault is full, response <15 min.",
    genres: ["OTOME", "SHOJO", "HORROR"],
    formats: ["VERTICAL_WEBTOON"],
    dealTypes: ["SWEAT_EQUITY_50_50", "PAID_GIG", "PORTFOLIO_BUILDING"],
    completionRate: 99,
    isVerified: true,
    ratingScore: 5.0,
    reviewCount: 28,
    completedProjects: 31,
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    location: "Madrid • CET",
    portfolio: [
      { id: "p6", title: "Crimson Petals — Color Script", url: "https://picsum.photos/seed/color1/800/1400", thumbnail: "https://picsum.photos/seed/color1/400/800", format: "VERTICAL_WEBTOON", type: "image" },
      { id: "p7", title: "Before/After — Flats to Render", url: "https://picsum.photos/seed/color2/800/800", thumbnail: "https://picsum.photos/seed/color2/400/400", format: "VERTICAL_WEBTOON", type: "image" },
    ],
    vault: [
      { id: "v4", title: "Speedpaint: Otome Blush Render", url: "https://picsum.photos/seed/vault4/600/400", thumbnail: "https://picsum.photos/seed/vault4/600/400", duration: "0:41", type: "speedpaint" },
      { id: "v5", title: "Workflow: Flat to Glow (Night Scene)", url: "https://picsum.photos/seed/vault5/600/400", thumbnail: "https://picsum.photos/seed/vault5/600/400", duration: "0:55", type: "workflow" },
    ]
  },
  {
    id: "u4",
    name: "Kenji & Haru — Studio Kōen",
    handle: "koen.studio",
    avatarUrl: "https://i.pravatar.cc/256?img=15",
    role: "WRITER",
    secondaryRoles: ["STORYBOARDER", "LINE_ARTIST"],
    bio: "Duo (Writer + Line Artist) seeking a COLORIST for a shōnen isekai. 20 pages scripted, names done. 50/50 split three ways. Featured on Jump Rookie.",
    genres: ["SHONEN", "ISEKAI"],
    formats: ["PAGE_MANGA"],
    dealTypes: ["SWEAT_EQUITY_50_50"],
    completionRate: 91,
    isVerified: true,
    ratingScore: 4.7,
    reviewCount: 18,
    completedProjects: 12,
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    location: "Kyoto • JST",
    portfolio: [
      { id: "p8", title: "Hollow Archive — Names (Storyboards)", url: "https://picsum.photos/seed/koen1/800/1200", thumbnail: "https://picsum.photos/seed/koen1/400/600", format: "PAGE_MANGA", type: "image", pages: ["https://picsum.photos/seed/koen1a/800/1200","https://picsum.photos/seed/koen1b/800/1200"] },
    ],
    vault: [
      { id: "v6", title: "Joint Pitch — 20s Trailer", url: "https://picsum.photos/seed/vault6/600/400", thumbnail: "https://picsum.photos/seed/vault6/600/400", duration: "0:26", type: "workflow" },
    ]
  },
  {
    id: "u5",
    name: "Priya Nair",
    handle: "priya.letters",
    avatarUrl: "https://i.pravatar.cc/256?img=26",
    role: "LETTERER",
    secondaryRoles: ["EDITOR"],
    bio: "Letterer & editor for indie webtoons. Clean SFX, adaptive balloons, RTL & vertical mastery. I make dialogue breathe. Portfolio clients: 3 Canvas Top 50.",
    genres: ["ROMANCE", "SLICE_OF_LIFE", "SHOJO"],
    formats: ["VERTICAL_WEBTOON", "PAGE_MANGA"],
    dealTypes: ["PAID_GIG", "SKILL_SWAP", "PORTFOLIO_BUILDING"],
    completionRate: 87,
    isVerified: false,
    ratingScore: 4.6,
    reviewCount: 22,
    completedProjects: 44,
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    location: "Mumbai • IST",
    portfolio: [
      { id: "p9", title: "Lettering Reel — Balloons & SFX", url: "https://picsum.photos/seed/letter1/800/1200", thumbnail: "https://picsum.photos/seed/letter1/400/600", format: "PAGE_MANGA", type: "image" },
    ],
    vault: [
      { id: "v7", title: "Workflow: SFX Integration (15s)", url: "https://picsum.photos/seed/vault7/600/400", thumbnail: "https://picsum.photos/seed/vault7/600/400", duration: "0:18", type: "workflow" },
    ]
  },
  {
    id: "u6",
    name: "Diego Alvarez",
    handle: "diego.ink",
    avatarUrl: "https://i.pravatar.cc/256?img=68",
    role: "STORYBOARDER",
    secondaryRoles: ["WRITER"],
    bio: "Name artist (nemu) — cinematic layouts. If your script is solid, I’ll make it sing. Looking for long-form seinen. Unverified but 95% completion — ask my past partners.",
    genres: ["SEINEN", "SCI_FI", "HORROR"],
    formats: ["PAGE_MANGA"],
    dealTypes: ["SWEAT_EQUITY_50_50", "PORTFOLIO_BUILDING"],
    completionRate: 95,
    isVerified: false,
    ratingScore: 4.8,
    reviewCount: 15,
    completedProjects: 9,
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    location: "Mexico City • CST",
    portfolio: [
      { id: "p10", title: "Name — Chapter 12 Thumbnails", url: "https://picsum.photos/seed/name1/800/1200", thumbnail: "https://picsum.photos/seed/name1/400/600", format: "PAGE_MANGA", type: "image", pages: ["https://picsum.photos/seed/name1a/800/1200","https://picsum.photos/seed/name1b/800/1200","https://picsum.photos/seed/name1c/800/1200"] },
    ],
    vault: [
      { id: "v8", title: "Name Breakdown: Action to Pause", url: "https://picsum.photos/seed/vault8/600/400", thumbnail: "https://picsum.photos/seed/vault8/600/400", duration: "0:36", type: "script_breakdown" },
    ]
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj1",
    title: "Spirit Bloom — Shōjo Cultivation Webtoon",
    description: "Aiko (Line) x Marcus (Writer) — 50/50 Pact sealed 12 days ago. Shōjo cultivation with ink-wash fights. Now in Line Art phase.",
    format: "VERTICAL_WEBTOON",
    genreTags: ["SHOJO", "CULTIVATION", "FANTASY"],
    dealType: "SWEAT_EQUITY_50_50",
    coverUrl: "https://picsum.photos/seed/project1/600/800",
    members: [{ userId: "u1", role: "LINE_ARTIST", equity: 50 }, { userId: "u2", role: "WRITER", equity: 50 }],
    milestones: [
      { title: "Script Approved", status: "COMPLETED", order: 1, completedAt: "2026-08-05" },
      { title: "Storyboard / Name", status: "COMPLETED", order: 2, completedAt: "2026-08-09" },
      { title: "Line Art", status: "IN_PROGRESS", order: 3 },
      { title: "Color & Lettering", status: "PENDING", order: 4 },
      { title: "Publish & Revenue Split", status: "PENDING", order: 5 },
    ],
    status: "ACTIVE",
  },
  {
    id: "proj2",
    title: "Dungeon Reborn: Floor 0",
    description: "Marcus + Sofia — LitRPG vertical. Escrow paid gig, milestone 2 funded. Ghost protection active — last activity 2h ago.",
    format: "VERTICAL_WEBTOON",
    genreTags: ["LITRPG", "ISEKAI"],
    dealType: "PAID_GIG",
    coverUrl: "https://picsum.photos/seed/project2/600/800",
    members: [{ userId: "u2", role: "WRITER", equity: 60 }, { userId: "u3", role: "COLORIST", equity: 40 }],
    milestones: [
      { title: "World Bible", status: "COMPLETED", order: 1 },
      { title: "Episode 1 Script", status: "IN_PROGRESS", order: 2 },
      { title: "Thumbs", status: "PENDING", order: 3 },
      { title: "Finals", status: "PENDING", order: 4 },
    ],
    status: "ACTIVE",
  },
];

export const mockSquads: StudioSquad[] = [
  {
    id: "s1",
    name: "Studio Kōen — Seeking Colorist",
    members: [mockUsers[3]],
    seeking: "COLORIST",
    genre: "SHONEN",
    format: "PAGE_MANGA",
    dealType: "SWEAT_EQUITY_50_50",
  },
  {
    id: "s2",
    name: "Neon Shrine — Writer + Artist seeking Letterer",
    members: [mockUsers[0], mockUsers[2]],
    seeking: "LETTERER",
    genre: "SEINEN",
    format: "VERTICAL_WEBTOON",
    dealType: "SWEAT_EQUITY_50_50",
  },
];

export const currentUser: User = {
  id: "me",
  name: "You",
  handle: "you.creator",
  avatarUrl: "https://i.pravatar.cc/256?img=33",
  role: "WRITER",
  secondaryRoles: [],
  bio: "Your profile — customize to get matched faster. Add your vault to enable 1-tap pacts.",
  genres: ["FANTASY", "SHONEN"],
  formats: ["VERTICAL_WEBTOON"],
  dealTypes: ["SWEAT_EQUITY_50_50"],
  completionRate: 100,
  isVerified: false,
  ratingScore: 5.0,
  reviewCount: 0,
  portfolio: [],
  vault: [
    { id: "vm1", title: "My Pitch — 30s Cold Open", url: "", thumbnail: "https://picsum.photos/seed/myvault1/600/400", duration: "0:32", type: "script_breakdown" },
    { id: "vm2", title: "Worldbuilding — Magic System", url: "", thumbnail: "https://picsum.photos/seed/myvault2/600/400", duration: "0:44", type: "workflow" },
  ],
  completedProjects: 0,
  lastActiveAt: new Date().toISOString(),
};
